/* A packrat parser generated by PackCC 3.0.0 */

#ifndef PCC_INCLUDED_ENVPARSER_H
#define PCC_INCLUDED_ENVPARSER_H

#ifdef __cplusplus
extern "C" {
#endif

typedef struct envparser_context_tag envparser_context_t;

envparser_context_t *envparser_create(void *auxil);
int envparser_parse(envparser_context_t *ctx, char**ret);
void envparser_destroy(envparser_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* !PCC_INCLUDED_ENVPARSER_H */
